services:

  postgres:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: auth-service
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_USER: auth_user
      DB_PASS: auth_password
      DB_NAME: auth_db
      JWT_SECRET: auth_super_secret
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    
  redis:
    image: redis:7
    container_name: session-redis
    ports:
      - "6379:6379"

  session-service:
    build:
      context: .
      dockerfile: services/session-service/Dockerfile
    container_name: session-service
    environment:
      PORT: 3000
      REDIS_HOST: redis
    ports:
      - "3002:3000"
    depends_on:
      - redis

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      PORT: 3000
      JWT_SECRET: supersecret
      REDIS_HOST: redis
    ports:
      - "3000:3000"
    depends_on:
      - redis

  call-state-manager:
    build: 
      context: .
      dockerfile: services/call-state-manager/Dockerfile
    container_name: call-state-manager
    environment:
      PORT: 3000
      REDIS_HOST: redis
    ports:
      - "3003:3000"
    depends_on:
      - redis

  switch-adapter:
    build: 
      context: .
      dockerfile: services/switch-adapter/Dockerfile
    container_name: switch-adapter
    environment:
      PORT: 3000
      FS_HOST: freeswitch
    ports:
      - "3004:3000"
    depends_on:
      - freeswitch

  freeswitch:
    image: safarov/freeswitch:latest
    container_name: freeswitch
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "8021:8021"
      - "17000-17999:17000-17999/udp"
    environment:
      SOUND_RATES: "8000:16000"
      SOUND_TYPES: "music:en-us-callie"
    volumes:
      - ./freeswitch/conf/vanilla:/etc/freeswitch
      - freeswitch_sounds:/usr/share/freeswitch/sounds
    tty: true
    restart: unless-stopped

volumes:
  auth_postgres_data:
  freeswitch_sounds: