services:

  base-service:
    build:
      context: .
      dockerfile: services/base-service/Dockerfile
    container_name: base-service
    environment:
      PORT: 3000
    ports:
      - "3001:3000"