services:

  auth-postgres:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: auth-service
    environment:
      PORT: 3000
      DB_HOST: auth-postgres
      DB_USER: auth_user
      DB_PASS: auth_password
      DB_NAME: auth_db
      JWT_SECRET: auth_super_secret
    ports:
      - "3001:3000"
    depends_on:
      - auth-postgres


  redis-session:
    image: redis:7
    container_name: session-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  session-service:
    build:
      context: .
      dockerfile: services/session-service/Dockerfile
    container_name: session-service
    environment:
      PORT: 3000
      REDIS_HOST: redis
    ports:
      - "3002:3000"
    depends_on:
      - redis


  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      PORT: 3000
      JWT_SECRET: auth_super_secret
      REDIS_HOST: redis
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - session-service
      - call-state-manager
      - billing-service


  call-state-manager:
    build:
      context: .
      dockerfile: services/call-state-manager/Dockerfile
    container_name: call-state-manager
    environment:
      PORT: 3000
      REDIS_HOST: redis
    ports:
      - "3003:3000"
    depends_on:
      - redis


  redis-signaling:
    image: redis:7

    container_name: signaling-redis

    ports:
      - "6379:6379"


  signaling-service:
    build:
      context: .
      dockerfile: services/signaling-service/Dockerfile

    container_name: signaling-service

    environment:
      PORT: 3010
      REDIS_HOST: redis

    ports:
      - "3010:3010"

    depends_on:
      - redis


  billing-postgres:
    image: postgres:15
    container_name: billing-db
    environment:
      POSTGRES_USER: billing_user
      POSTGRES_PASSWORD: billing_password
      POSTGRES_DB: billing_db
    ports:
      - "5433:5432"
    volumes:
      - billing_postgres_data:/var/lib/postgresql/data


  billing-service:
    build:
      context: .
      dockerfile: services/billing-service/Dockerfile
    container_name: billing-service
    environment:
      PORT: 3000
      DB_HOST: billing-postgres
      DB_USER: billing_user
      DB_PASS: billing_password
      DB_NAME: billing_db
    ports:
      - "3005:3000"
    depends_on:
      - billing-postgres


  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  event-bus:
    build:
      context: .
      dockerfile: services/event-bus/Dockerfile
    container_name: event-bus
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  call-history-postgres:
    image: postgres:15
    container_name: call-history-db
    environment:
      POSTGRES_USER: history_user
      POSTGRES_PASSWORD: history_password
      POSTGRES_DB: history_db
    ports:
      - "5434:5432"
    volumes:
      - history_postgres_data:/var/lib/postgresql/data

  call-history-service:
    build: 
      context: .
      dockerfile: services/call-history-service/Dockerfile
    container_name: call-history-service
    environment:
      DB_HOST: call-history-postgres
      DB_USER: history_user
      DB_PASS: history_password
      DB_NAME: history_db
    ports:
      - "3006:3000"
    depends_on:
      - call-history-postgres

volumes:
  auth_postgres_data:
  freeswitch_sounds:
  billing_postgres_data:
  history_postgres_data:
  redis_data: