global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "backend"

    scrape_configs:
      - job_name: "services"
        static_configs:
          - targets:
              - auth-service:3000
              - session-service:3000
              - api-gateway:3000
              - call-state-manager:3000
              - billing-service:3000