export enum CallEventType {

  CALL_CREATED = "CALL_CREATED",

  CALL_RINGING = "CALL_RINGING",

  CALL_ANSWERED = "CALL_ANSWERED",

  CALL_REJECTED = "CALL_REJECTED",

  CALL_MISSED = "CALL_MISSED",

  CALL_ENDED = "CALL_ENDED",

  CALL_FAILED = "CALL_FAILED"

}