export const SIGNALING_EVENTS = {

  CALL_USER: "CALL_USER",

  INCOMING_CALL: "INCOMING_CALL",

  ACCEPT_CALL: "ACCEPT_CALL",

  CALL_ACCEPTED: "CALL_ACCEPTED",

  REJECT_CALL: "REJECT_CALL",

  CALL_REJECTED: "CALL_REJECTED",

  END_CALL: "END_CALL",

  CALL_ENDED: "CALL_ENDED",

  WEBRTC_OFFER: "WEBRTC_OFFER",

  WEBRTC_ANSWER: "WEBRTC_ANSWER",

  ICE_CANDIDATE: "ICE_CANDIDATE"

};